# Generated by Django 3.0.8 on 2020-08-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edutitle', models.CharField(blank=True, max_length=100, null=True)),
                ('eduDateTo', models.DateField(blank=True, null=True)),
                ('eduDateFrom', models.DateField(blank=True, null=True)),
                ('eduFrom', models.CharField(blank=True, max_length=100, null=True)),
                ('eduDis', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='experiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('dis1', models.CharField(blank=True, max_length=200, null=True)),
                ('dis2', models.CharField(blank=True, max_length=200, null=True)),
                ('dis3', models.CharField(blank=True, max_length=200, null=True)),
                ('dis4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='basic',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
