# Generated by Django 3.0.8 on 2020-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
