# Generated by Django 3.0.8 on 2020-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200830_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
