# Generated by Django 3.0.8 on 2020-08-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='skype',
            new_name='telegram',
        ),
    ]
