# Generated by Django 3.0.8 on 2020-09-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='avail',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
